name: Master workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Java application and run test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unitary test
        run: mvn -B -Dtest="es/urjc/realfood/restaurants/unit/*" -DfailIfNoTests=false test
      - name: Run integration test
        run: mvn -B -Dtest="es/urjc/realfood/restaurants/integration/*" -DfailIfNoTests=false test

  publish-github-packages:
    name: Upload Maven Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build project with Maven
        run: mvn -B package -DskipTests
      - name: Set app version to env var
        run: echo "APP_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_ENV
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYYMMDDHHmmss'
      - name: Publish package
        run: |
          mvn versions:set -DnewVersion=$TIME--${{ env.APP_VERSION }}
          mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIME: "${{ steps.time.outputs.time }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1

  publish-docker-image:
    name: Upload Docker Image
    runs-on: ubuntu-latest
    needs: [ publish-github-packages ]
    env:
      IMAGE_NAME: es.urjc.realfood.restaurants
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Download jar from previous job
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target
      - name: Set app version to env var
        run: echo "APP_VERSION=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_ENV
      - name: Build image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE_NAME .
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Push image to DockerHub
        run: |
          IMAGE_VERSION=${{ env.APP_VERSION }}
          docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_ORG }}/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_ORG }}/$IMAGE_NAME:$IMAGE_VERSION
          docker push --all-tags ${{ secrets.DOCKERHUB_ORG }}/$IMAGE_NAME
      - name: Login to Docker GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push image to Docker GitHub Packages
        run: |
          IMAGE_VERSION=${{ env.APP_VERSION }}
          IMAGE_USER=$(echo ${{ github.repository }} | awk '{print tolower($0)}')
          docker tag $IMAGE_NAME docker.pkg.github.com/$IMAGE_USER/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME docker.pkg.github.com/$IMAGE_USER/$IMAGE_NAME:$IMAGE_VERSION
          docker push --all-tags docker.pkg.github.com/$IMAGE_USER/$IMAGE_NAME