kind: PersistentVolume
apiVersion: v1
metadata:
  name: realfood-restaurants-mongo-pv
spec:
  storageClassName: "realfood-restaurants-mongo-sc"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /realfood-restaurants-mongo-data