apiVersion: apps/v1
kind: Deployment
metadata:
  name: realfood-restaurants-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realfood-restaurants-mongo
  template:
    metadata:
      labels:
        app: realfood-restaurants-mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: realfood-restaurants
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
          image: postgres
          imagePullPolicy: IfNotPresent
          name: realfood-mongo-postgres
          ports:
            - containerPort: 27017
      restartPolicy: Always
      volumes:
        - name: realfood-restaurants-mongo-persistent-storage
          persistentVolumeClaim:
            claimName: realfood-restaurants-mongo-pv-claim