apiVersion: v1
kind: Service
metadata:
  labels:
    app: realfood-restaurants-mongo
  name: realfood-restaurants-mongo
spec:
  type: ClusterIP
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: realfood-restaurants-mongo