apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: realfood-restaurants-mongo-pv-claim
  labels:
    app: realfood-restaurants-mongo
spec:
  storageClassName: "realfood-restaurants-mongo-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi